/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPrayerRequestsRouteImport } from './routes/_app/prayer-requests'
import { Route as AppRemindersRouteImport } from './routes/_app/reminders'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTestimoniesRouteImport } from './routes/_app/testimonies'
import { Route as AppAttendanceIndexRouteImport } from './routes/_app/attendance/index'
import { Route as AppAttendanceServiceIdRouteImport } from './routes/_app/attendance/$serviceId'
import { Route as AppContributionsIndexRouteImport } from './routes/_app/contributions/index'
import { Route as AppContributionsFundIdRouteImport } from './routes/_app/contributions/$fundId'
import { Route as AppMinistriesIndexRouteImport } from './routes/_app/ministries/index'
import { Route as AppMinistriesDepartmentIdRouteImport } from './routes/_app/ministries/$departmentId'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppPeoplePersonIdRouteImport } from './routes/_app/people/$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPrayerRequestsRoute = AppPrayerRequestsRouteImport.update({
  id: '/prayer-requests',
  path: '/prayer-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTestimoniesRoute = AppTestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceServiceIdRoute = AppAttendanceServiceIdRouteImport.update({
  id: '/attendance/$serviceId',
  path: '/attendance/$serviceId',
  getParentRoute: () => AppRoute,
} as any)
const AppContributionsIndexRoute = AppContributionsIndexRouteImport.update({
  id: '/contributions/',
  path: '/contributions/',
  getParentRoute: () => AppRoute,
} as any)
const AppContributionsFundIdRoute = AppContributionsFundIdRouteImport.update({
  id: '/contributions/$fundId',
  path: '/contributions/$fundId',
  getParentRoute: () => AppRoute,
} as any)
const AppMinistriesIndexRoute = AppMinistriesIndexRouteImport.update({
  id: '/ministries/',
  path: '/ministries/',
  getParentRoute: () => AppRoute,
} as any)
const AppMinistriesDepartmentIdRoute =
  AppMinistriesDepartmentIdRouteImport.update({
    id: '/ministries/$departmentId',
    path: '/ministries/$departmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/prayer-requests': typeof AppPrayerRequestsRoute
  '/reminders': typeof AppRemindersRoute
  '/settings': typeof AppSettingsRoute
  '/testimonies': typeof AppTestimoniesRoute
  '/attendance/$serviceId': typeof AppAttendanceServiceIdRoute
  '/contributions/$fundId': typeof AppContributionsFundIdRoute
  '/ministries/$departmentId': typeof AppMinistriesDepartmentIdRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/attendance/': typeof AppAttendanceIndexRoute
  '/contributions/': typeof AppContributionsIndexRoute
  '/ministries/': typeof AppMinistriesIndexRoute
  '/people/': typeof AppPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/prayer-requests': typeof AppPrayerRequestsRoute
  '/reminders': typeof AppRemindersRoute
  '/settings': typeof AppSettingsRoute
  '/testimonies': typeof AppTestimoniesRoute
  '/attendance/$serviceId': typeof AppAttendanceServiceIdRoute
  '/contributions/$fundId': typeof AppContributionsFundIdRoute
  '/ministries/$departmentId': typeof AppMinistriesDepartmentIdRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/attendance': typeof AppAttendanceIndexRoute
  '/contributions': typeof AppContributionsIndexRoute
  '/ministries': typeof AppMinistriesIndexRoute
  '/people': typeof AppPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/prayer-requests': typeof AppPrayerRequestsRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/testimonies': typeof AppTestimoniesRoute
  '/_app/attendance/$serviceId': typeof AppAttendanceServiceIdRoute
  '/_app/contributions/$fundId': typeof AppContributionsFundIdRoute
  '/_app/ministries/$departmentId': typeof AppMinistriesDepartmentIdRoute
  '/_app/people/$personId': typeof AppPeoplePersonIdRoute
  '/_app/attendance/': typeof AppAttendanceIndexRoute
  '/_app/contributions/': typeof AppContributionsIndexRoute
  '/_app/ministries/': typeof AppMinistriesIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/prayer-requests'
    | '/reminders'
    | '/settings'
    | '/testimonies'
    | '/attendance/$serviceId'
    | '/contributions/$fundId'
    | '/ministries/$departmentId'
    | '/people/$personId'
    | '/attendance/'
    | '/contributions/'
    | '/ministries/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/prayer-requests'
    | '/reminders'
    | '/settings'
    | '/testimonies'
    | '/attendance/$serviceId'
    | '/contributions/$fundId'
    | '/ministries/$departmentId'
    | '/people/$personId'
    | '/attendance'
    | '/contributions'
    | '/ministries'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/prayer-requests'
    | '/_app/reminders'
    | '/_app/settings'
    | '/_app/testimonies'
    | '/_app/attendance/$serviceId'
    | '/_app/contributions/$fundId'
    | '/_app/ministries/$departmentId'
    | '/_app/people/$personId'
    | '/_app/attendance/'
    | '/_app/contributions/'
    | '/_app/ministries/'
    | '/_app/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prayer-requests': {
      id: '/_app/prayer-requests'
      path: '/prayer-requests'
      fullPath: '/prayer-requests'
      preLoaderRoute: typeof AppPrayerRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/testimonies': {
      id: '/_app/testimonies'
      path: '/testimonies'
      fullPath: '/testimonies'
      preLoaderRoute: typeof AppTestimoniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/': {
      id: '/_app/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/$serviceId': {
      id: '/_app/attendance/$serviceId'
      path: '/attendance/$serviceId'
      fullPath: '/attendance/$serviceId'
      preLoaderRoute: typeof AppAttendanceServiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contributions/': {
      id: '/_app/contributions/'
      path: '/contributions'
      fullPath: '/contributions/'
      preLoaderRoute: typeof AppContributionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contributions/$fundId': {
      id: '/_app/contributions/$fundId'
      path: '/contributions/$fundId'
      fullPath: '/contributions/$fundId'
      preLoaderRoute: typeof AppContributionsFundIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ministries/': {
      id: '/_app/ministries/'
      path: '/ministries'
      fullPath: '/ministries/'
      preLoaderRoute: typeof AppMinistriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ministries/$departmentId': {
      id: '/_app/ministries/$departmentId'
      path: '/ministries/$departmentId'
      fullPath: '/ministries/$departmentId'
      preLoaderRoute: typeof AppMinistriesDepartmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$personId': {
      id: '/_app/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPrayerRequestsRoute: typeof AppPrayerRequestsRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTestimoniesRoute: typeof AppTestimoniesRoute
  AppAttendanceServiceIdRoute: typeof AppAttendanceServiceIdRoute
  AppContributionsFundIdRoute: typeof AppContributionsFundIdRoute
  AppMinistriesDepartmentIdRoute: typeof AppMinistriesDepartmentIdRoute
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
  AppContributionsIndexRoute: typeof AppContributionsIndexRoute
  AppMinistriesIndexRoute: typeof AppMinistriesIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPrayerRequestsRoute: AppPrayerRequestsRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTestimoniesRoute: AppTestimoniesRoute,
  AppAttendanceServiceIdRoute: AppAttendanceServiceIdRoute,
  AppContributionsFundIdRoute: AppContributionsFundIdRoute,
  AppMinistriesDepartmentIdRoute: AppMinistriesDepartmentIdRoute,
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
  AppContributionsIndexRoute: AppContributionsIndexRoute,
  AppMinistriesIndexRoute: AppMinistriesIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
